# Generated by Django 5.2.7 on 2025-11-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vesselcategory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vesselcategory',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
