# Generated by Django 5.2.7 on 2025-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv_main', '0002_alter_vessel_description_alter_vessel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vesselcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vesselcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
