# Generated by Django 5.2.7 on 2025-11-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv_main', '0004_alter_vessel_image_alter_vesselcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='image',
            field=models.ImageField(blank=True, upload_to='vessels'),
        ),
        migrations.AlterField(
            model_name='vesselcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='vessels_cats/'),
        ),
    ]
