# Generated by Django 5.2.7 on 2025-11-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv_main', '0005_alter_vessel_image_alter_vesselcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sv_main.vesselcategory'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='image',
            field=models.ImageField(blank=True, upload_to='vessels/'),
        ),
    ]
