# Generated by Django 6.0 on 2025-12-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv_main', '0009_remove_results_results_results_final_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='weigth',
            field=models.JSONField(default={'a': 0, 'b': 0, 'c': 0}),
        ),
    ]
