# Generated by Django 6.0 on 2025-12-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sv_main', '0010_answer_weigth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='weight_a',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='weight_b',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='weight_c',
        ),
    ]
