# Generated by Django 6.0.1 on 2026-01-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv_main', '0012_alter_results_final_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselcategory',
            name='rating',
        ),
        migrations.AlterField(
            model_name='answer',
            name='weigth',
            field=models.JSONField(default='0 0 0'),
        ),
        migrations.AlterField(
            model_name='results',
            name='final_answer',
            field=models.JSONField(default={'a': 0, 'b': 0, 'c': 0}),
        ),
    ]
