# Generated by Django 6.0 on 2026-01-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv_main', '0012_alter_results_final_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VesselCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Vessel',
            new_name='Item',
        ),
        migrations.AlterField(
            model_name='answer',
            name='weigth',
            field=models.JSONField(default='0 0 0'),
        ),
        migrations.AlterField(
            model_name='results',
            name='final_answer',
            field=models.JSONField(default={'a': 0, 'b': 0, 'c': 0}),
        ),
        migrations.AlterModelTable(
            name='category',
            table='sv_main_vesselcategory',
        ),
    ]
