# Generated by Django 6.0 on 2026-01-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sv_main', '0013_rename_vesselcategory_category_rename_vessel_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='rating',
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
