# Generated by Django 6.0 on 2026-01-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv_main', '0014_remove_category_rating_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
